language: java
sudo: false
jdk:
  - oraclejdk8
script: mvn clean package
notifications:
  email:
    recipients:
      - dominique.righetto@gmail.com
    on_failure: always
addons:
  coverity_scan:
    project:
      name: "righettod/virtualhost-payload-generator"
      description: "Trigger via TravisCI"
    notification_email: dominique.righetto@gmail.com
    build_command: mvn clean package
    branch_pattern: master    